-- #######################################################################################
-- AUTOGENERATED HYPR CONFIG.
-- PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,
-- OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
-- #######################################################################################

--
-- Please note not all available settings / options are set here.
-- For a full list, see the wiki
--

-- autogenerated = 1 # remove this line to remove the warning

-- See https://wiki.hyprland.org/Configuring/Monitors/
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "eDP-1",
    mode = "2560x1600@60.00100",
    position = "0x0",
    scale = "1.6",
})

-- See https://wiki.hyprland.org/Configuring/Keywords/ for more
hl.env("GDK_SCALE", "0.5")
hl.env("XCURSOR_SIZE", "16")

-- Execute your favorite apps at launch
--#exec-once = garuda-welcome

-- Add networkmanager applet to tray in waybar
-- exec-once = nm-applet --indicator

hl.env("SHELL", "/usr/bin/fish")
-- for davinki
-- hl.env("QT_QPA_PLATFORM", "xcb")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "3")
hl.env("QT_WAYLAND_FORCE_DPI", "96")
hl.env("CHROME_EXECUTABLE", "zen-browser")
hl.env("FLUTTER_ROOT", "/home/soilad/develop/flutter")

-- Set keyboard layout
--exec-once = .local/bin/garuda-locale.sh

-- Set monitor values. For own values, please comment with #
--#exec-once = .local/bin/mon.sh

-- Source a file (multi-file configs)
-- source = ~/.config/hypr/myColors.conf

-- For all categories, see https://wiki.hyprland.org/Configuring/Variables/

hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 7,
    bezier = "myBezier",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 7,
    bezier = "default",
    style = "popin 80%",
})
hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 7,
    bezier = "default",
    style = "popin 80%",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 10,
    bezier = "default",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 7,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 6,
    bezier = "default",
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})

local mainMod = "SUPER"

hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("hyprctl reload"))
hl.bind(mainMod .. " + code:36", hl.dsp.exec_cmd("kitty"))
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd("kitty"))
hl.bind(mainMod .. " + Z", hl.dsp.window.close())
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exec_cmd("nwgbar"))
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("thunar"))
hl.bind(mainMod .. " + SHIFT + code:65", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("emote"))
hl.bind(mainMod .. " + SHIFT + D", hl.dsp.exec_cmd("nwg-drawer -mb 10 -mr 10 -ml 10 -mt 10"))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())

hl.bind("CTRL + ALT + delete", hl.dsp.exec_cmd("~/.config/eww/scripts/toggle.sh status"))
hl.bind(mainMod .. " + SUPER_L", hl.dsp.exec_cmd("~/.config/eww/scripts/toggle.sh search"))
hl.bind(mainMod .. " + escape", hl.dsp.exec_cmd("eww close search | eww close status"))
hl.bind(mainMod .. " + SHIFT + P", hl.dsp.exec_cmd("hyprshot -m region"))

hl.bind(mainMod .. " + F1", hl.dsp.exec_cmd("firedragon"))
hl.bind(mainMod .. " + F2", hl.dsp.exec_cmd("thunderbird"))
hl.bind(mainMod .. " + F3", hl.dsp.exec_cmd("thunar"))
hl.bind(mainMod .. " + F4", hl.dsp.exec_cmd("geany"))
hl.bind(mainMod .. " + F5", hl.dsp.exec_cmd("github-desktop"))
hl.bind(mainMod .. " + F6", hl.dsp.exec_cmd("gparted"))
hl.bind(mainMod .. " + F7", hl.dsp.exec_cmd("inkscape"))
hl.bind(mainMod .. " + F8", hl.dsp.exec_cmd("blender"))
hl.bind(mainMod .. " + F9", hl.dsp.exec_cmd("meld"))
hl.bind(mainMod .. " + F10", hl.dsp.exec_cmd("joplin-desktop"))
hl.bind(mainMod .. " + F11", hl.dsp.exec_cmd("snapper-tools"))
hl.bind(mainMod .. " + F12", hl.dsp.exec_cmd("galculator"))

hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

hl.bind("ALT + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind("ALT + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind("ALT + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind("ALT + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind("ALT + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind("ALT + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind("ALT + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind("ALT + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind("ALT + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind("ALT + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1, follow = false }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2, follow = false }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3, follow = false }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4, follow = false }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5, follow = false }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6, follow = false }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7, follow = false }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8, follow = false }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9, follow = false }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10, follow = false }))

hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

hl.bind("switch:on:Lid Switch", hl.dsp.exec_cmd("notify-send \"Lid closed - ignoring\""), { locked = true })
hl.bind("switch:off:Lid Switch", hl.dsp.exec_cmd("notify-send \"Lid opened\""), { locked = true })

hl.bind("code:122", hl.dsp.exec_cmd("pamixer --decrease 5; notify-send \" Volume: \"$(pamixer --get-volume) -t 500"))
hl.bind("code:123", hl.dsp.exec_cmd("pamixer --increase 5; notify-send \" Volume: \"$(pamixer --get-volume) -t 500"))
hl.bind("code:121", hl.dsp.exec_cmd("pamixer --toggle-mute; notify-send \" Volume: Toggle-mute\" -t 500"))
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("pactl set-source-mute @DEFAULT_SOURCE@ toggle; notify-send \"System Mic: Toggle-mute\" -t 500"))

hl.bind(mainMod .. " + O", hl.dsp.exec_cmd("firedragon"))
hl.bind(mainMod .. " + M", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.fullscreen_state({ internal = 0, client = 2, action = "toggle" }))
hl.bind("code:232", hl.dsp.exec_cmd("brightnessctl -c backlight set 5%-"))
hl.bind("code:233", hl.dsp.exec_cmd("brightnessctl -c backlight set +5%"))
hl.bind(mainMod .. " + SHIFT + C", hl.dsp.exec_cmd("killall -9 wpaperd && wpaperd"))

hl.bind("Print", hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | swappy -f -"))
hl.bind("CTRL + Print", hl.dsp.exec_cmd(".config/hypr/scripts/screenshot_window.sh"))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd(".config/hypr/scripts/screenshot_display.sh"))

hl.bind(mainMod .. " + R", hl.dsp.submap("resize"))

hl.define_submap("resize", function()

    hl.bind("right", hl.dsp.window.resize({ x = 50, y = 0, relative = true }), { repeating = true })
    hl.bind("L", hl.dsp.window.resize({ x = 50, y = 0, relative = true }), { repeating = true })
    hl.bind("left", hl.dsp.window.resize({ x = -50, y = 0, relative = true }), { repeating = true })
    hl.bind("H", hl.dsp.window.resize({ x = -50, y = 0, relative = true }), { repeating = true })
    hl.bind("up", hl.dsp.window.resize({ x = 0, y = -50, relative = true }), { repeating = true })
    hl.bind("K", hl.dsp.window.resize({ x = 0, y = -50, relative = true }), { repeating = true })
    hl.bind("down", hl.dsp.window.resize({ x = 0, y = 50, relative = true }), { repeating = true })
    hl.bind("J", hl.dsp.window.resize({ x = 0, y = 50, relative = true }), { repeating = true })

    hl.bind("escape", hl.dsp.submap("reset"))
end)

hl.bind(mainMod .. " + SHIFT + up", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + SHIFT + down", hl.dsp.window.move({ direction = "d" }))
hl.bind(mainMod .. " + SHIFT + J", hl.dsp.window.move({ direction = "d" }))
hl.bind(mainMod .. " + SHIFT + left", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + SHIFT + H", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "r" }))
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.window.move({ direction = "r" }))

hl.bind(mainMod .. " + SHIFT + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "+0" }))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.workspace.toggle_special("magic"))

-- TODO: manual review — top-level key 'blurls = wofi' has no enclosing section
-- TODO: manual review — top-level key 'blurls = thunar' has no enclosing section
-- TODO: manual review — top-level key 'blurls = gedit' has no enclosing section
-- TODO: manual review — top-level key 'blurls = gtk-layer-shell' has no enclosing section
-- TODO: manual review — top-level key 'blurls = catfish' has no enclosing section

hl.bind("SUPER + V", hl.dsp.exec_cmd("cliphist list | wofi --dmenu | cliphist decode | wl-copy"))

hl.bind("code:172", hl.dsp.exec_cmd("playerctl play-pause"))
hl.bind("code:171", hl.dsp.exec_cmd("playerctl next"))
hl.bind("code:173", hl.dsp.exec_cmd("playerctl previous"))

hl.bind(mainMod .. " + SHIFT + G", hl.dsp.exec_cmd("footclient -e ~/.local/bin/bear/implement_gum.sh enable"))
hl.bind(mainMod .. " + I", hl.dsp.exec_cmd(".local/bin/calamares.sh"))

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

-- Keyboard backlight
hl.bind("XF86KbdBrightnessUp",
    hl.dsp.exec_cmd("brightnessctl -d :white:kbd_backlight set +2%"),
    { repeating = true, locked = true }
)

hl.bind("XF86KbdBrightnessDown",
    hl.dsp.exec_cmd("brightnessctl -d :white:kbd_backlight set 2%-"),
    { repeating = true, locked = true }
)

hl.config({
    input = {
        kb_layout = "us",
        kb_variant = "",
        kb_model = "",
        kb_options = "",
        kb_rules = "",
        numlock_by_default = true,
        follow_mouse = 1,
        touchpad = {
            natural_scroll = true,
            tap_to_click = false,
            disable_while_typing = true,
            clickfinger_behavior = true,
        },
        sensitivity = -0.3, -- -1.0 - 1.0, 0 means no modification.
    },
    general = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
        gaps_in = 5,
        gaps_out = 5,
        border_size = 3,
        col = {
            active_border = { colors = { "rgba(ff0000ee)", "rgba(660000ee)" }, angle = 45 },
            inactive_border = "rgba(000000e6)",
        },
        layout = "dwindle",
    },
    decoration = {
        -- active_opacity = 0.95,
        -- inactive_opacity = 0.9,
        active_opacity = 0.85,
        inactive_opacity = 0.8,
        fullscreen_opacity = 1.0,
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
        rounding = 24,
        blur = {
            enabled = false,
            size = 8,
            passes = 3,
        },
        shadow = {
            -- sharp = true
            -- offset = 2 2
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(000000aa)",
        },
    },
    animations = {
        enabled = true,
        -- Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
    },
    dwindle = {
        -- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
        -- pseudotile = true # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
        preserve_split = true, -- you probably want this
    },
    master = {
        -- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
        new_status = "master",
    },
    -- gesture = 3, down, dispatcher, exec, eww open search
    -- gesture = 3, up, dispatcher, exec, eww close search
    misc = {
        disable_hyprland_logo = true,
    },
    -- Example per-device config
    -- See https://wiki.hyprland.org/Configuring/Keywords/
    -- executing for more
    --device:epic mouse V1 {
    --   sensitivity = -0.5
    --}
    -- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
    -- Example windowrule v1
    -- windowrule = float, title:(^(kitty)$)
    -- windowrule = float, title:(^(garuda-assistant)$)
    -- windowrule = float, title:(^(garuda-boot-options)$)
    -- windowrule = float, title:(^(garuda-boot-repair)$)
    -- windowrule = float, title:(^(garuda-gamer)$)
    -- windowrule = float, title:(^(garuda-network-assistant)$)
    -- windowrule = float, title:(^(garuda-settings-manager)$)
    -- windowrule = float, title:(^(garuda-welcome)$)
    -- windowrule = float, title:(^(calamares)$)
    -- Example windowrule v2
    -- windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
    -- See https://wiki.hyprland.org/Configuring/Keywords/ for more
    -- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
    -- bindr=SUPER, SUPER_L, exec, pkill wofi || wofi --normal-window --show drun --allow-images
    -- bind = $mainMod SHIFT, P, togglesplit, # dwindle
    --custom shi
    -- Mainmod + Function keys
    -- Move focus with mainMod + arrow keys
    -- Switch workspaces with mainMod + [0-9]
    -- Move to workspace with focused container with ALT + SHIFT + [0-9]
    -- Move active window to a workspace with mainMod + SHIFT + [0-9]
    -- Scroll through existing workspaces with mainMod + scroll
    -- Move/resize windows with mainMod + LMB/RMB and dragging
    -- background
    -- exec-once = mpvpaper -o "--loop" ALL /usr/share/wallpapers/soilad-wallpapers/wonderjoker-persona-p5x.1920x1080.mp4
    -- status bar
    -- layerrule = blur , eww
    -- layerrule = ignorezero , eww
    -- set volume (laptops only and may or may not work on PCs)
    -- other bindings
    -- Screenshots:
    --
    -- Change to swappy https://github.com/jtheoof/swappy
    -- Old functions only commented out to make it easier for the user to change if necessary.
    -- Snip a selection and pipe to swappy
    -- Screenshot a window and pipe to swappy
    -- Screenshot the current display and pipe to swappy
    -- https://github.com/hyprwm/contrib/blob/main/grimblast/grimblast.1.scd
    -- Print: All outputs
    -- SHIFT+Print: Select area
    -- $mainMod+Print: Current window
    -- $mainMod+Shfit+Print: Current output
    --
    -- bind = ,Print, exec, grimblast save screen && notify-send Screenshot captured
    -- bind = SHIFT, Print, exec, grimblast save area && notify-send Selected\ area captured
    -- bind = $mainMod, Print, exec, grimblast save active && notify-send Active\ window captured
    -- bind = $mainMod SHIFT, Print, exec, grimblast output active && notify-send Output captured
    -- for resizing window
    -- will switch to a submap called resize
    -- will start a submap called "resize"
    -- sets repeatable binds for resizing the active window
    -- use reset to go back to the global submap
    -- will reset the submap, meaning end the current one and return to the global one
    -- to move window
    -- special workspace
    -- other blurings
    -- window rules
    -- windowrule v1 syntax is gone. windowrule now behaves like windowrulev2, deprecating the windowrulev2 keyword
    -- windowrule = opacity 0.85 override 0.85 override,title:(^(thunar)$)
    --
    -- windowrule = opacity 0.85 override 0.85 override,title:(^(gedit)$)
    -- windowrule = opacity 0.85 override 0.85 override,title:(^(catfish)$)
    -- windowrule = stayfocused, title:(^(wofi)$)
    -- window rules with evaluation
    -- windowrulev2 = opacity 0.85 0.85,floating:1
    -- exec-once = mako
    -- experimental(might work might won't)
    -- pre executions (under development)
    -- Clipboard Manager
    -- video play paues bindings
    -- Use gtk-settings
    -- Performance Tweaks (For less power consumption without sacrificing performance)
    -- See : https://wiki.hyprland.org/Configuring/Performance/
    -- misc:vfr = true
    -- enable G-Hyprland
    -- Install Garuda Hyprland
    -- some env variables
    -- we usually prefer things to be set up through script
    -- have a look at hyprstart file
    --# Hypr Ecosystem
    -- hypridle
    xwayland = {
        force_zero_scaling = true,
    },
})

hl.on("hyprland.start", function()
    -- hl.exec_cmd("wpaperd &")
    hl.exec_cmd("wpaperctl set /usr/share/wallpapers/soilad-wallpapers/wallpaper.png")
    hl.exec_cmd("hyprpm reload")
    hl.exec_cmd("eww open-many top-bar bgclock wallpaper stupid-fucking-reverse-corners")
    hl.exec_cmd("~/.config/eww/scripts/initvars.sh")
    hl.exec_cmd("~/.cargo/bin/end-rs daemon")
    hl.exec_cmd("dbus-update-activation-environment --all")
    hl.exec_cmd("systemd-inhibit --what=handle-lid-switch sleep 0")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("foot --server")
    hl.exec_cmd("exec xrdb -load ~/.Xresources")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("apply-gsettings")
    hl.exec_cmd("hypridle")
end)

if hl.plugin.hyprglass then
    local hg = hl.plugin.hyprglass

    hg.config({
        default_theme = "dark",
        default_preset = "soilad",

        dark = { brightness = 0.82 },
        light = { adaptive_boost = 0.5 },

        layers = { enabled = 1 },
    })

    -- Layer surfaces: each call whitelists the namespace and configures it
    hg.layer("waybar", { preset = "subtle", mask_threshold = 0.05 })
    hg.layer("eww", { preset = "soilad", mask_threshold = 0.5 })
    hg.layer("swaync")
    hg.layer("quickshell:bezel", { preset = "ui", mask_threshold = 0.3 })
    hg.layer("debug-panel", { exclude = true })

    -- Presets

    hg.preset("soilad", {
        glass_opacity = 1.0,
        blur_strength = 0.4,
        refraction_strength = 0.9,
        fresnel_strength = 0.0,
        edge_thickness = 0.08,
        lens_distortion = 1.0,
        brightness = 1.0,
        saturation = 0.6,
        vibrancy = 1.0,
        vibrancy_darkness = 1.0,
    })

    hg.preset("clear", {
        glass_opacity = 0.8,
        blur_strength = 1.5,
        -- blur_strength = 0.0,
        dark = { brightness = 0.7 },
        light = { brightness = 1.2 },
    })

    hg.preset("contrasted", {
        inherits = "high_contrast",
        contrast = 1.2,
        adaptive_dim = 1.5,
        dark = { tint_color = 0x02142aa9 },
    })
end
